//
//  CCEffectDFInnerGlow.h
//  cocos2d-ios
//
//  Created by Oleg Osin on 9/11/14.
//
//

#import "CCEffect.h"

/**
 * CCEffectDFInnerGlow create a drop shadow.
 *
 */
#if CC_EFFECTS_EXPERIMENTAL

@interface CCEffectDFInnerGlow : CCEffect

/// -----------------------------------------------------------------------
/// @name Accessing Effect Attributes
/// -----------------------------------------------------------------------

/** Color of the outline */
@property (nonatomic, strong) CCColor* fillColor;

/** Color of the distance field */
@property (nonatomic, strong) CCColor* outlineColor;

/** Outline width pixel width of the outline */
@property (nonatomic) int outlineWidth;

// Distance Field, generated by SDFGen (https://github.com/osinoleg/SDFGen)
@property (nonatomic, strong) CCTexture* distanceField;

/// -----------------------------------------------------------------------
/// @name Initializing a CCEffectDFInnerGlow object
/// -----------------------------------------------------------------------

/**
 *  Initializes a CCEffectDFInnerGlow object with a (5, -5) black drop shadow offset .
 *
 *  @return The CCEffectDFInnerGlow object.
 */
-(id)init;

/**
 *  Initializes a CCEffectDFInnerGlow object with the supplied parameters.
 *
 *  @param outlineColor Color of the outline, a [CCColor blackColor] will result in an opaque black outline.
 *  @param fillColor Color of the fillColor, a [CCColor blackColor] will result in an opaque black fillColor.
 *  @param outlineWidth pixel width of the outline.
 *  @param fieldScale, defined by the distance field generation proccess, for example a distance field that
 *  was generated with a 4096/4096 input and output a 128/128 texture would have a fieldScale of 32 (
 *  input size / output size). Note: this parameter could be automatically calculated if we assume that all
 *  distance fields are generated from a 4096 input.
 *
 *  @return The CCEffectDFInnerGlow object.
 */
-(id)initWithOutlineColor:(CCColor*)outlineColor fillColor:(CCColor*)outlineColor outlineWidth:(int)outlineWidth fieldScale:(float)fieldScale distanceField:(CCTexture*)distanceField;


/// -----------------------------------------------------------------------
/// @name Creating a CCEffectDFInnerGlow object
/// -----------------------------------------------------------------------

/**
 *  Initializes a CCEffectDFInnerGlow object with the supplied parameters.
 *
 *  @param glowColor Color of the glow, a [CCColor blackColor] will result in an opaque black drop shadow.
 *
 *  @return The CCEffectDFInnerGlow object.
 */
+(id)effectWithOutlineColor:(CCColor*)outlineColor fillColor:(CCColor*)fillColor outlineWidth:(int)outlineWidth fieldScale:(float)fieldScale distanceField:(CCTexture*)distanceField;

@end

#endif

